In [1]:
# Cell 1: Import libraries and modules
import torch
import import_ipynb
from data_preprocessing import process_band
from data_combiner import combine_band_data
from analysis_pipeline import run_all_analyses
from netwrks_2 import MultiBandAttentionFusion






# Cell 2: Load your data
PATH_TO_SAVED_DYNAMIC_alpha = r"C:\Users\fathi\test\Granger_all_dynamic_data_overlap50.pt"
PATH_TO_SAVED_DYNAMIC_beta = r"C:\Users\fathi\test\Granger_all_dynamic_data_overlap50_beta.pt"

dynamic_data_alpha_raw = torch.load(PATH_TO_SAVED_DYNAMIC_alpha)
dynamic_data_beta_raw = torch.load(PATH_TO_SAVED_DYNAMIC_beta)

# Cell 3: Process each band
train_alpha, test_alpha, dynamic_alpha = process_band(dynamic_data_alpha_raw)
train_beta, test_beta, dynamic_beta = process_band(dynamic_data_beta_raw)

print(f"Alpha band: {len(dynamic_alpha)} subjects")
print(f"Beta band: {len(dynamic_beta)} subjects")

# Cell 4: Combine bands for multi-band analysis
band_data_list = [dynamic_alpha, dynamic_beta]
combined_dataset = combine_band_data(band_data_list)
band_names = ['Alpha', 'Beta']

print(f"Combined dataset: {len(combined_dataset)} subjects")

# Cell 5: Run analysis
results = run_all_analyses(combined_dataset, model_class=MultiBandAttentionFusion, band_names=band_names)
# Cell 6: Access results
best_model = results['best_single_model']
ensemble_model = results['ensemble_model']
fold_metrics = results['fold_metrics']
cv_results = results['cv_results']

print("\nFinal Results:")
print(f"Best CV F1: {cv_results['avg_f1']:.4f}")
print(f"Best CV Accuracy: {cv_results['avg_accuracy']:.4f}")
if cv_results['avg_band_importance']:
    print("Band Importance:")
    for band, importance in cv_results['avg_band_importance'].items():
        print(f"  {band}: {importance:.4f}")

# Cell 7: Optional - Save models
torch.save(best_model.state_dict(), 'best_model.pt')
torch.save(ensemble_model.state_dict(), 'ensemble_model.pt')

C:\Users\fathi\AppData\Local\Temp\ipykernel_23236\3204851067.py:18: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  dynamic_data_alpha_raw = torch.load(PATH_TO_SAVED_DYNAMIC_a

Alpha band: 52 subjects
Beta band: 52 subjects
Combined dataset: 52 subjects
Using device: cpu

===== Fold 1/5 =====
Training set: Class 0: 23, Class 1: 18
Validation set: Class 0: 6, Class 1: 5


c:\Users\fathi\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\optim\lr_scheduler.py:62: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(


Using class weights: [0.8913044 1.7083334]


Training Fold 1:   0%|          | 0/1 [00:00<?, ?it/s]c:\Users\fathi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
Training Fold 1: 100%|██████████| 1/1 [00:57<00:00, 57.87s/it, best_epoch=1, best_f1=0.3850, conf=0.99, train_loss=1.7856, val_f1=0.3850, val_loss=2.2881]



Fold 1 - Best Epoch: 1
Best Validation F1: 0.3850
Accuracy: 0.5455 | Recall: 0.5455 | Precision: 0.2975
Average prediction confidence: 0.9936
Confusion Matrix:
[[6 0]
 [5 0]]

Band Importance Analysis (Fold 1):
Alpha: 0.9741 (97.4%)
Beta: 0.0259 (2.6%)

===== Fold 2/5 =====
Training set: Class 0: 23, Class 1: 18
Validation set: Class 0: 6, Class 1: 5


c:\Users\fathi\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\optim\lr_scheduler.py:62: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(


Using class weights: [0.8913044 1.7083334]


Training Fold 2:   0%|          | 0/1 [00:00<?, ?it/s]c:\Users\fathi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
Training Fold 2: 100%|██████████| 1/1 [00:52<00:00, 52.90s/it, best_epoch=1, best_f1=0.3850, conf=0.97, train_loss=1.6911, val_f1=0.3850, val_loss=1.5965]



Fold 2 - Best Epoch: 1
Best Validation F1: 0.3850
Accuracy: 0.5455 | Recall: 0.5455 | Precision: 0.2975
Average prediction confidence: 0.9676
Confusion Matrix:
[[6 0]
 [5 0]]

Band Importance Analysis (Fold 2):
Alpha: 0.9856 (98.6%)
Beta: 0.0144 (1.4%)

===== Fold 3/5 =====
Training set: Class 0: 24, Class 1: 18
Validation set: Class 0: 5, Class 1: 5


c:\Users\fathi\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\optim\lr_scheduler.py:62: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(


Using class weights: [0.875 1.75 ]


Training Fold 3:   0%|          | 0/1 [00:00<?, ?it/s]c:\Users\fathi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
Training Fold 3: 100%|██████████| 1/1 [00:54<00:00, 54.39s/it, best_epoch=1, best_f1=0.3333, conf=0.97, train_loss=2.1910, val_f1=0.3333, val_loss=1.7556]



Fold 3 - Best Epoch: 1
Best Validation F1: 0.3333
Accuracy: 0.5000 | Recall: 0.5000 | Precision: 0.2500
Average prediction confidence: 0.9690
Confusion Matrix:
[[5 0]
 [5 0]]

Band Importance Analysis (Fold 3):
Alpha: 0.9903 (99.0%)
Beta: 0.0097 (1.0%)

===== Fold 4/5 =====
Training set: Class 0: 23, Class 1: 19
Validation set: Class 0: 6, Class 1: 4


c:\Users\fathi\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\optim\lr_scheduler.py:62: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(


Using class weights: [0.9130435 1.6578947]


Training Fold 4: 100%|██████████| 1/1 [00:54<00:00, 54.80s/it, best_epoch=1, best_f1=0.3429, conf=0.52, train_loss=2.0289, val_f1=0.3429, val_loss=0.7069]



Fold 4 - Best Epoch: 1
Best Validation F1: 0.3429
Accuracy: 0.4000 | Recall: 0.4000 | Precision: 0.3000
Average prediction confidence: 0.5156
Confusion Matrix:
[[4 2]
 [4 0]]

Band Importance Analysis (Fold 4):
Alpha: 0.9941 (99.4%)
Beta: 0.0059 (0.6%)

===== Fold 5/5 =====
Training set: Class 0: 23, Class 1: 19
Validation set: Class 0: 6, Class 1: 4


c:\Users\fathi\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\optim\lr_scheduler.py:62: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(


Using class weights: [0.9130435 1.6578947]


Training Fold 5:   0%|          | 0/1 [00:00<?, ?it/s]c:\Users\fathi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
Training Fold 5: 100%|██████████| 1/1 [00:59<00:00, 59.72s/it, best_epoch=1, best_f1=0.4500, conf=0.98, train_loss=2.1695, val_f1=0.4500, val_loss=1.6110]


Fold 5 - Best Epoch: 1
Best Validation F1: 0.4500
Accuracy: 0.6000 | Recall: 0.6000 | Precision: 0.3600
Average prediction confidence: 0.9820
Confusion Matrix:
[[6 0]
 [4 0]]

Band Importance Analysis (Fold 5):
Alpha: 0.0288 (2.9%)
Beta: 0.9712 (97.1%)

===== Cross-Validation Results =====
Average F1: 0.3792
Average Accuracy: 0.5182
Average Recall: 0.5182
Average Precision: 0.3010
F1 Standard Deviation: 0.0412

Average Band Importance Across All Folds:
Alpha: 0.7946 (79.5%)
Beta: 0.2054 (20.5%)

===== Analysis Summary =====
Cross-Validation F1: 0.3792 ± 0.0412
Cross-Validation Accuracy: 0.5182 ± 0.0671

Final Results:
Best CV F1: 0.3792
Best CV Accuracy: 0.5182
Band Importance:
  Alpha: 0.7946
  Beta: 0.2054
